import type { Metadata } from "next";
import "./globals.css";
import Nav from "./component/nav";

export const metadata: Metadata = {
  title: "Rest Country",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <link rel="shortcut icon" href="sad.png" type="image/x-icon" />
      <body className="bg-[#202c37] text-white dark:text-gray-900 dark:bg-white flex flex-col item-center">
        <Nav />
        {children}
      </body>
    </html>
  );
}
